image: centos:7

before_script:
 - yum -y install gcc && yum clean all
 - curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
 - bash miniconda.sh -b -p /opt/miniconda
 - export PATH="/opt/miniconda/bin:$PATH"
 - conda update conda
 - conda env create -f environment.yml
 - source activate particleman
 - echo "$PATH"
 - conda list
 - pip install .

tests:
 stage: test
 script:
   - py.test -v
# when: manual
