name: particleman-dev
channels:
- defaults # prioritize defaults
- conda-forge
dependencies:
- recommonmark
- setuptools>=38.6
- sphinx
- sphinx_rtd_theme
- fftw
- python=3
- numpy
- matplotlib
- pytest
- pip
- pip:
    - -e .  #install current package editable 
