site_name: Particle Man
site_url: https://lanl-seismoacoustics.github.io/particleman
site_description: Particle Motion Analysis of Seismic Surface Waves

repo_url: http://github.com/lanl-seismoacoustics/particleman

pages:
- 'Home': 'index.md'
- 'Comparison to Other Transforms': 'comparison.md'
- 'Basic Usage': 'basic.md'
- 'Plotting': 'plotting.md'
- 'Filtering': 'filtering.md'
- 'API Documentation': 'api.md'
- 'License': 'license.md'

docs_dir: 'src'
site_dir: 'html'
theme: 'readthedocs'
